### ISSUE TITLE
尊敬的开发者您好！有一个打包问题想请教一下

### ISSUE THREAD

**Issue by jzw814321930** [SkiTiSu/TEditor#3]
![image](https://user-images.githubusercontent.com/47199213/183864365-468c658e-3c86-4acb-b9d3-fe03524e7421.png)
正常打包后报错136个重复性错误，请问怎么解决呀

**Comment by SkiTiSu** [comment]
这个是WPF的一个bug，刚刚更新的master已经在csproj中增加了workaroud，可以再试一下~

**Comment by jzw814321930** [comment]
完美！~谢谢开发者

**Comment by SkiTiSu** [comment]
好的，有问题欢迎继续交流
