### ISSUE TITLE
缺失字符 FallBack 机制

### ISSUE THREAD

**Issue by MixBadGun** [SkiTiSu/TEditor#4]
由于标题多样，导致单个字体处理后的文本有些字符会显示为方框。或许可以添加一种 FallBack 机制？

**Comment by SkiTiSu** [comment]
抱歉今天才看到，字体的问题是由于程序使用了WPF的渲染所导致，之前有尝试过解决，但是没有找到好的办法。可能可以调用系统API对每个字进行检测后替换单字（还会引入排版问题，大概相当于自己写一个文字渲染库了），或者换用skia等处理得更好的库重写渲染部分，抑或是用Web技术重构本程序的部分功能。目前没有太多精力维护本程序，如果你有好的建议欢迎继续留言。
